package com.bhx.workDemo;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

/**
 * 根据请求百可录的报文，调整题目
 */
public class AdjustExamPro {

    public static void main(String[] args) {
        int ipId = 4589094;
//        String text1 = "{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"8997a1200a474b2c9035e3f67eaa50a6\",\"work_data\":{\"phone_num\":\"13949972816\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"您的工作地在哪个省？\",\"sort\":2,\"proCode\":\"49\",\"selection\":{\"b\":\"河北省\",\"c\":\"山东省\",\"a\":\"河南省\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":3,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"您在除银行之外的其他机构信用贷款有几笔？\",\"sort\":4,\"proCode\":\"93\",\"selection\":{\"b\":\"1至3笔\",\"c\":\"3笔以上\",\"a\":\"0笔\"}},{\"text\":\"请问联系人白利玲的手机运营商是？\",\"sort\":5,\"paramMap\":{\"contactHolder\":\"白利玲\"},\"proCode\":\"8\",\"selection\":{\"b\":\"中国移动\",\"c\":\"中国联通\",\"a\":\"中国电信\"}},{\"text\":\"您身份证住址所在的城市是哪个？\",\"sort\":6,\"proCode\":\"3\",\"selection\":{\"b\":\"漯河市\",\"c\":\"许昌市\",\"a\":\"周口市\"}},{\"text\":\"“华满发，鲜春华”是你们公司的员工吗？\",\"sort\":7,\"paramMap\":{\"contactHolder1\":\"华满发\",\"contactHolder2\":\"鲜春华\"},\"proCode\":\"15\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您的最高学历是？\",\"sort\":8,\"proCode\":\"10\",\"selection\":{\"b\":\"高中/中专/技校\",\"c\":\"本科\",\"a\":\"硕士及以上\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":9,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"男\",\"name\":\"郝俊辉\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text2 = "{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"dd33f25929274dcfbbec586ee8253f47\",\"work_data\":{\"phone_num\":\"15058554209\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"您身份证住址所在的城市是哪个？\",\"sort\":2,\"proCode\":\"3\",\"selection\":{\"b\":\"金华市\",\"c\":\"自贡市\",\"a\":\"内江市\"}},{\"text\":\"请问联系人徐聪的手机运营商是？\",\"sort\":3,\"paramMap\":{\"contactHolder\":\"徐聪\"},\"proCode\":\"8\",\"selection\":{\"b\":\"中国移动\",\"c\":\"中国联通\",\"a\":\"中国电信\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":4,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"您的常住地是哪个城市？\",\"sort\":5,\"proCode\":\"20\",\"selection\":{\"b\":\"金华市\",\"c\":\"巴中市\",\"a\":\"广元市\"}},{\"text\":\"您是否曾有借款不还的现象？\",\"sort\":6,\"proCode\":\"97\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您从住所到公司大约有几公里？\",\"sort\":7,\"proCode\":\"19\",\"selection\":{\"b\":\"7至11公里\",\"c\":\"13至17公里\",\"a\":\"1至5公里\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":8,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"您的工作地在哪个省？\",\"sort\":9,\"proCode\":\"49\",\"selection\":{\"b\":\"浙江省\",\"c\":\"宁夏回族自治区\",\"a\":\"江西省\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"女\",\"name\":\"耿梦欢\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text = "{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"4ece419576864d56a77df049a537da8f\",\"work_data\":{\"phone_num\":\"13452752782\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"您的申请表填写的收入水平范围是多少？\",\"sort\":2,\"proCode\":\"48\",\"selection\":{\"b\":\"5000-7000\",\"c\":\"7000以上\",\"a\":\"5000以下\"}},{\"text\":\"请问联系人李红的手机运营商是？\",\"sort\":3,\"paramMap\":{\"contactHolder\":\"李红\"},\"proCode\":\"8\",\"selection\":{\"b\":\"中国移动\",\"c\":\"中国联通\",\"a\":\"中国电信\"}},{\"text\":\"“饶秋佳，罗舒允”是你们公司的员工吗？\",\"sort\":4,\"paramMap\":{\"contactHolder1\":\"饶秋佳\",\"contactHolder2\":\"罗舒允\"},\"proCode\":\"15\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"未来的6个月内您有没有信用卡提现的打算？\",\"sort\":5,\"proCode\":\"103\",\"selection\":{\"b\":\"无\",\"a\":\"有\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":6,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"您申请的借款金额在哪个范围内？\",\"sort\":7,\"proCode\":\"35\",\"selection\":{\"b\":\"14000-16000\",\"c\":\"16000以上\",\"a\":\"14000以下\"}},{\"text\":\"请在bee一声之后输入您的身份证号码后四位以#号键结束，字母请用*代替。\",\"sort\":8,\"proCode\":\"4\"},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":9,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"女\",\"name\":\"张燕\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text="{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"39b4809e78df4d8a9e5d83e3a9d81988\",\"work_data\":{\"phone_num\":\"18620145279\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"您和家人最近一次旅行有多久了？\",\"sort\":2,\"proCode\":\"99\",\"selection\":{\"b\":\"1年内\",\"c\":\"1年以上\",\"a\":\"半年内\"}},{\"text\":\"请在bee一声之后输入您的身份证号码后四位以#号键结束，字母请用*代替。\",\"sort\":3,\"proCode\":\"4\"},{\"text\":\"您申请的借款金额在哪个范围内？\",\"sort\":4,\"proCode\":\"35\",\"selection\":{\"b\":\"19000-21000\",\"c\":\"21000以上\",\"a\":\"19000以下\"}},{\"text\":\"“刘宝河，项金华”是你们公司的员工吗？\",\"sort\":5,\"paramMap\":{\"contactHolder1\":\"刘宝河\",\"contactHolder2\":\"项金华\"},\"proCode\":\"15\",\"selection\":{\"b\":\"是\",\"a\":\"否\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":6,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"您从住所到公司大约有几公里？\",\"sort\":7,\"proCode\":\"19\",\"selection\":{\"b\":\"53至73公里\",\"c\":\"83至103公里\",\"a\":\"23至43公里\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":8,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"请问您提供的父母的名字是哪一个？\",\"sort\":9,\"paramMap\":{\"relationHolder\":\"父母\"},\"proCode\":\"16\",\"selection\":{\"b\":\"廖祖维\",\"c\":\"徐凤云\",\"a\":\"于满春\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"女\",\"name\":\"于艳平\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text="{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"9902002f12cd444cb800ff2c843285ac\",\"work_data\":{\"phone_num\":\"13333032452\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"您从住所到公司大约有几公里？\",\"sort\":2,\"proCode\":\"19\",\"selection\":{\"b\":\"12至18公里\",\"c\":\"21至27公里\",\"a\":\"3至9公里\"}},{\"text\":\"您的工作地在哪个省？\",\"sort\":3,\"proCode\":\"49\",\"selection\":{\"b\":\"内蒙古自治区\",\"c\":\"河北省\",\"a\":\"青海省\"}},{\"text\":\"请问赵秀珍是否在恒昌借款成功过？\",\"sort\":4,\"paramMap\":{\"contactHolder\":\"赵秀珍\"},\"proCode\":\"25\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您的联系人冯小东是否在本公司借款成功过？\",\"sort\":5,\"paramMap\":{\"contactHolder\":\"冯小东\"},\"proCode\":\"58\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":6,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"请问以下哪个选项是您身份证上出生年份对应的生肖属相？\",\"sort\":7,\"proCode\":\"5\",\"selection\":{\"b\":\"猴\",\"c\":\"龙\",\"a\":\"猪\"}},{\"text\":\"您经常在哪个APP上购物？\",\"sort\":8,\"proCode\":\"101\",\"selection\":{\"b\":\"淘宝\",\"c\":\"其他\",\"a\":\"京东\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":9,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"女\",\"name\":\"冯小燕\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text="{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"4adb18ecf8c742d59d7b501fed0d1929\",\"work_data\":{\"phone_num\":\"13955875699\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"未来的6个月内您有没有信用卡提现的打算？\",\"sort\":2,\"proCode\":\"103\",\"selection\":{\"b\":\"无\",\"a\":\"有\"}},{\"text\":\"“梁炳池，卢海超”是你们公司的员工吗？\",\"sort\":3,\"paramMap\":{\"contactHolder1\":\"梁炳池\",\"contactHolder2\":\"卢海超\"},\"proCode\":\"15\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":4,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"您的联系人王亚利是否在本公司借款成功过？\",\"sort\":5,\"paramMap\":{\"contactHolder\":\"王亚利\"},\"proCode\":\"58\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":6,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"您的申请表填写的收入水平范围是多少？\",\"sort\":7,\"proCode\":\"48\",\"selection\":{\"b\":\"9000-11000\",\"c\":\"11000以上\",\"a\":\"9000以下\"}},{\"text\":\"您身份证住址所在的城市是哪个？\",\"sort\":8,\"proCode\":\"3\",\"selection\":{\"b\":\"阜阳市\",\"c\":\"淮南市\",\"a\":\"芜湖市\"}},{\"text\":\"请问您提供的父母的名字是哪一个？\",\"sort\":9,\"paramMap\":{\"relationHolder\":\"父母\"},\"proCode\":\"16\",\"selection\":{\"b\":\"吕宏富\",\"c\":\"杨平心\",\"a\":\"李文兰\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"男\",\"name\":\"张振成\"}},\"work_id\":\"work_id4_jsd\"}";
//        String text="{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"0961e48392e642fa92fc5f772f87d1c2\",\"work_data\":{\"phone_num\":\"15867180954\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"未来的6个月内您有没有信用卡提现的打算？\",\"sort\":2,\"proCode\":\"103\",\"selection\":{\"b\":\"无\",\"a\":\"有\"}},{\"text\":\"请问以下哪个选项是您身份证上出生年份对应的生肖属相？\",\"sort\":3,\"proCode\":\"5\",\"selection\":{\"b\":\"猪\",\"c\":\"鸡\",\"a\":\"蛇\"}},{\"text\":\"您单位有没有固定的销售渠道？\",\"sort\":4,\"proCode\":\"85\",\"selection\":{\"b\":\"没有\",\"a\":\"有\"}},{\"text\":\"您的常住地是哪个城市？\",\"sort\":5,\"proCode\":\"20\",\"selection\":{\"b\":\"嘉兴市\",\"c\":\"丽水市\",\"a\":\"杭州市\"}},{\"text\":\"您的工作地在哪个省？\",\"sort\":6,\"proCode\":\"49\",\"selection\":{\"b\":\"河南省\",\"c\":\"浙江省\",\"a\":\"湖北省\"}},{\"text\":\"“廖祖维，李永焕”是你们公司的员工吗？\",\"sort\":7,\"paramMap\":{\"contactHolder1\":\"廖祖维\",\"contactHolder2\":\"李永焕\"},\"proCode\":\"15\",\"selection\":{\"b\":\"是\",\"a\":\"否\"}},{\"text\":\"请问李柏林是否在恒昌借款成功过？\",\"sort\":8,\"paramMap\":{\"contactHolder\":\"李柏林\"},\"proCode\":\"25\",\"selection\":{\"b\":\"否\",\"a\":\"是\"}},{\"text\":\"您经营单位回款周期多长时间？\",\"sort\":9,\"proCode\":\"84\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"男\",\"name\":\"李水明\"}},\"work_id\":\"work_id4_jsd\"}";
        String text="{\"access_token\":\"af18489907f181ccd836ee29b8974b9f\",\"corp_code\":\"hc_jsd_credit_examine\",\"job_code\":\"HYR-SP-003\",\"order_id\":\"462022806b654bb6861583c3db5373da\",\"work_data\":{\"phone_num\":\"13828982065\",\"call_num\":2,\"exam\":[{\"text\":\"请问您本次申请的恒易贷即速贷业务是否为您本人提出?本人申请请按1，未申请请按2\",\"sort\":1,\"paramMap\":{\"product\":\"即速贷\"},\"proCode\":\"1\"},{\"text\":\"请问您提供的父母的名字是哪一个？\",\"sort\":2,\"paramMap\":{\"relationHolder\":\"父母\"},\"proCode\":\"16\",\"selection\":{\"b\":\"陈锦凤\",\"c\":\"朱军利\",\"a\":\"鲜春华\"}},{\"text\":\"您的申请表填写的收入水平范围是多少？\",\"sort\":3,\"proCode\":\"48\",\"selection\":{\"b\":\"6500-8500\",\"c\":\"8500以上\",\"a\":\"6500以下\"}},{\"text\":\"用于治疗什么病？\",\"sort\":4,\"proCode\":\"70\",\"selection\":{\"b\":\"癌症肿瘤\",\"c\":\"其他\",\"a\":\"常见感冒发烧\"}},{\"text\":\"您身份证上出生日期对应的星座是？\",\"sort\":5,\"proCode\":\"7\",\"selection\":{\"b\":\"双子座\",\"c\":\"巨蟹座\",\"a\":\"摩羯座\"}},{\"text\":\"您平时会去哪些地方购买日用生活用品？\",\"sort\":6,\"proCode\":\"100\",\"selection\":{\"b\":\"上网购买\",\"c\":\"其他人购买\",\"a\":\"超市\"}},{\"text\":\"“吕泽程，饶秋佳”是你们公司的员工吗？\",\"sort\":7,\"paramMap\":{\"contactHolder1\":\"吕泽程\",\"contactHolder2\":\"饶秋佳\"},\"proCode\":\"15\",\"selection\":{\"b\":\"是\",\"a\":\"否\"}},{\"text\":\"请问以下哪个选项是您身份证上出生年份对应的生肖属相？\",\"sort\":8,\"proCode\":\"5\",\"selection\":{\"b\":\"猪\",\"c\":\"鼠\",\"a\":\"虎\"}},{\"text\":\"治愈后恢复需要多长时间？\",\"sort\":9,\"proCode\":\"73\",\"selection\":{\"b\":\"半年到1年\",\"c\":\"一年以上\",\"a\":\"半年内\"}},{\"text\":\"为确保您的借款用途真实、并证实是您本人完成上面的互动，请在滴声后输入您的电话号码，并按#结束。\",\"sort\":10,\"proCode\":\"14\"}],\"info\":{\"sex\":\"男\",\"name\":\"陈曾炳艮\"}},\"work_id\":\"work_id4_jsd\"}";
        JSONObject jsonObject = JSON.parseObject(text);
        JSONArray jsonArray = jsonObject.getJSONObject("work_data").getJSONArray("exam");
        for (int i = 0; i <jsonArray.size() ; i++) {
            JSONObject json =jsonArray.getJSONObject(i);
            int seqno =i+1;
            if (seqno>1 && seqno<10){
//                String sql = "UPDATE eagle_jsd_voice_exam SET exam_code="+json.getIntValue("proCode")+",question='"+json.getString("text")+"',answer_choice='"+json.getString("selection")+"',answer_correct='#' WHERE ip_id="+ipId+" AND seqno="+seqno+";";
                String sql = "UPDATE eagle_jsd_voice_exam SET seqno="+seqno+",question='"+json.getString("text")+"',answer_choice='"+json.getString("selection")+"',answer_correct='#' WHERE ip_id="+ipId+" AND exam_code="+json.getIntValue("proCode")+";";
                System.out.println(sql);
            }
        }
    }
}
